### PR TITLE
Upper case man section references

### PR DESCRIPTION
**Pull request by AlainODea**
Make man page references consistent with Illumos by upper-casing man section references.

### CODE REVIEW

**Comment by bahamas10** [comment]
@AlainODea thanks for PR.  A couple of files have (undoubtedly) changed in the last 2 years breaking this change.  If you want to rebase this against the latest master and update your commit I'm happy to get this in the master ASAP.  Thanks!

**Comment by alain-odea-vgh** [comment]
Great stuff.  Thank you Dave.  I'll take a crack at this once the kids are in bed :)

**Comment by AlainODea** [comment]
@bahamas10 this should merge cleanly now.  Thanks again.

**Comment by bahamas10** [comment]
@AlainODea thanks! a public ticket has been created here https://smartos.org/bugview/OS-4711

and your change has landed in this commit https://github.com/joyent/smartos-live/commit/d5dab2ac009edde28dadd084d1a2d490eb31e214

**Pull request closed without merging**
