### PR TITLE
OS-8316 vminfod client shouldn't attempt to cleanup on a ready timeout

### PR DESCRIPTION
**Pull request by papertigers**

### CODE REVIEW

**Review by danmcd — DISMISSED** [review]
Seems simple enough.

**Comment by papertigers** [comment]
Turns out `_abort()` calls `stop()` which calls `_clearReadyTimeout()`.  
So I am opting for sticking on an additional property so that its easy to find with mdb.

**Comment by papertigers** [comment]
cc @bahamas10 if you have time and wouldn't mind looking this over.

**Review by danmcd — APPROVED** [review]

**Comment by bahamas10** [comment]
this change looks good to me! i like the idea.  one small nit: initialize `self.vs_ready_timeout_fired = false` when the object is created so it always exists.  otherwise, LGTM

**Comment by danmcd** [comment]
Please update the bug report with testing done, and your recent analysis to change the approach mentioned above in this PR.

**Review by danmcd — APPROVED** [review]
Make sure testing & analysis goes in the bug report.  I can IA once it does.

**Pull request merged**
