### PR TITLE
OS-8234 illumos-joyent should use jdk11 for builds

### PR DESCRIPTION
**Pull request by jasonbking**

### CODE REVIEW

**Comment by danmcd** [comment]
I'm wondering if we could jump right to openjdk11?

**Comment by jperkin** [comment]
In terms of package availability, yes, openjdk11-11.0.2 is available in 2018Q4 onwards.

**Review by danmcd — APPROVED** [review]
Ship it!

**Review by jperkin — APPROVED** [review]
Yeh assuming the build looks good it's a +1 from me too, we build openjdk11 out of our custom repository so should be very future-proof from a packaging perspective.

**Pull request merged**
