### PR TITLE
Add Cyberpower USB vendor class

### PR DESCRIPTION
**Pull request by leaberry**
This will make cyberpower usb UPS units attach to the ugen driver so apcupsd can use them. Fixes Issue #566

### CODE REVIEW

**Comment by rmustacc** [comment]
Hmm. I'm wondering if we should actually just be identifying this class and leveraging some of the hid logic to have it always bind to ugen regardless.

**Comment by leaberry** [comment]
I discovered after a number of hours that my cyberpower UPS won't work with apcupsd (wrong protocol) so I'm not as interested in getting this merged. But the guy from Issue #566 is probably interested.

I don't have any opinions on the best implementation.

**Comment by ismell** [comment]
leaberry@ did you ever figure out a way of using your cyperpower UPS?

**Comment by rmustacc** [comment]
@ismell Assuming that this is showing up as a hid device, all hid devices should show up with ugen nodes you can use now instead, so in theory the logic here should no longer be necessary.

**Comment by leaberry** [comment]
@ismell I never got it working. The ugen part worked fine but apcupsd didn't support the cyberpower protocol for my UPS

**Comment by razamatan** [comment]
i'm the guy from #566... if i undo my manual workaround, should things just work in the current release?

**Pull request closed without merging**
