### PR TITLE
Fix setup of encrypted zpool when setting up a new compute node

### LINKED ISSUE #1020: Creation of encrypted zpool during CN setup broken
Reproduce (on a Triton headnode with a new computenode, YubiKey inserted):
PI: `20220118T183559Z`
```
sdc-server setup -s $UUID encryption_enabled=true
```

Logs:
```
...
[2022-03-23T11:18:22Z] ./joysetup.sh:969: main(): create_zpool zones /tmp/pool.json
[2022-03-23T11:18:22Z] ./joysetup.sh:458: create_zpool(): SYS_ZPOOL=zones
[2022-03-23T11:18:22Z] ./joysetup.sh:459: create_zpool(): POOL_JSON=/tmp/pool.json
[2022-03-23T11:18:22Z] ./joysetup.sh:460: create_zpool(): local e_flag=
[2022-03-23T11:18:22Z] ./joysetup.sh:461: create_zpool(): local bootable=no
[2022-03-23T11:18:22Z] ./joysetup.sh:463: create_zpool(): [[ -n '' ]]
[2022-03-23T11:18:22Z] ./joysetup.sh:472: create_zpool(): [[ -n 1 ]]
[2022-03-23T11:18:22Z] ./joysetup.sh:472: create_zpool(): e_flag='-e '
[2022-03-23T11:18:22Z] ./joysetup.sh:474: create_zpool(): /usr/sbin/zpool list -H -o name zones
cannot open 'zones': no such pool
[2022-03-23T11:18:22Z] ./joysetup.sh:475: create_zpool(): printf %-56s 'creating pool: zones'
[2022-03-23T11:18:22Z] ./joysetup.sh:480: create_zpool(): mkzpool -B -f -e zones /tmp/pool.json
fatal error: pool creation failed: create-zpool: illegal option -- B
Unknown option -B
Usage: kbmadm create-zpool [-g guid] [-t template] -- <zpool create args>...
       kbmadm recover [-c cfgnum] dataset
       kbmadm unlock [-r] dataset...
       kbmadm recovery add [-a] [-t template] [-r recovery_token] dataset
       kbmadm recovery list [-p] dataset
       kbmadm recovery activate dataset
       kbmadm recovery cancel dataset

[2022-03-23T11:18:23Z] ./joysetup.sh:483: create_zpool(): mkzpool -f -e zones /tmp/pool.json
fatal error: pool creation failed: create-zpool: illegal option -- f
Unknown option -f
Usage: kbmadm create-zpool [-g guid] [-t template] -- <zpool create args>...
       kbmadm recover [-c cfgnum] dataset
       kbmadm unlock [-r] dataset...
       kbmadm recovery add [-a] [-t template] [-r recovery_token] dataset
       kbmadm recovery list [-p] dataset
       kbmadm recovery activate dataset
       kbmadm recovery cancel dataset

[2022-03-23T11:18:23Z] ./joysetup.sh:484: create_zpool(): printf '%6s\n' failed
[2022-03-23T11:18:23Z] ./joysetup.sh:485: create_zpool(): fatal 'failed to create pool'
[2022-03-23T11:18:23Z] ./joysetup.sh:172: fatal(): echo 'Error: failed to create pool'
[2022-03-23T11:18:23Z] ./joysetup.sh:173: fatal(): exit 1
```

### PR DESCRIPTION
**Pull request by teutat3s**
Fixes #1020

### CODE REVIEW

**Comment by jasonbking** [comment]
While it no longer counts, +1 from me.

**Comment by bahamat** [comment]
@jasonbking it definitely counts.

@teutat3s have you been able to properly test this? If so, please add testing output to #1020. If you need a test platform built, let me know.

**Comment by jasonbking** [comment]
@bahamat Not to GitHub (what I meant) :)

**Comment by danmcd** [comment]
I likely broke this with the RFD 176 support.  What I'm not seeing here nor in #1020 is why this broke.  Since I broke it, I'll provide an analysis text both here, and in #1020 :

_The kbmadm(1M-soon-to-be-8) man page states clearly that its ZFS pool creation arguments to appear after a "--", as they are passed straight into zpool(1M-soon-to-be-8). For some reason (and upon reading the source history of zfs.js I'm wondering if it ever did, as the "--" requirement was always there, maybe the introduction of "-f" in zfs.js?) the zfs.js caller does not insert the required "--" and things go sideways. _

**Review by danmcd — DISMISSED** [review]
I wonder why nobody saw this earlier?  Good catch, regardless.  Esp. glad that @jasonbking approves too.

**Comment by jasonbking** [comment]
Yeah -- that might have been a bug in the original bit I added that got surfaced with the latter changes... since getopt() stops at either '--' or a non argument, if could be the latter was causing the kbmadm specific flag processing to stop previously.

**Comment by blackwood821** [comment]
I think the issue was introduced in this commit:
https://github.com/joyent/smartos-live/commit/da5a7509459e7599610dd1c2644f3b98a6fa0332#diff-61b2771ed09ddd69a765a254a7b1727b7661f7985441194591b8e44cb284f007R143

which changed from:
```
args = [ 'create', '-f', pool ];
```

to:
```
cmd = exports.paths.kbmadm;
args = [ 'create-zpool' ];
```

So `--` was never in there.

**Comment by danmcd** [comment]
Also TIL, Jenkins won't run from a non-core-contributor PR.  I've kicked that off now.

**Review by danmcd — APPROVED** [review]
Will defer IA to @bahamat , but please make sure "Reviewed-by: Jason King <....>" is added to the commit message.

**Pull request merged**
