### PR TITLE
Trivial manpage fix. gz -> gzip.

### PR DESCRIPTION
**Pull request by OranguTech**
#Fixes[ 690](https://github.com/joyent/smartos-live/issues/690)

(This is my first public contribution/PR, any suggestions/corrections welcome)

### CODE REVIEW

**Comment by trentm** [comment]
Hi @Scandalon, Thanks for the PR! This repo doesn't use GitHub PRs, but instead uses Gerrit (a different change review system) hosted at https://cr.joyent.us.

I was going to point you to the README section that mentioned this, but I see that we haven't updated this repo's README to point to Gerrit. I've opened https://smartos.org/bugview/OS-5899 to handling updating the README.

There is a User Guide for using cr.joyent.us here: https://github.com/joyent/joyent-gerrit/blob/master/docs/user/README.md
Let me know whether or not you are able to add a CR to Gerrit there. Then we can close this PR. Thanks!

**Comment by Scandalon** [comment]
Thanks Trent. Yes, that was very confusing, and, well, still is. ("Wrong documentation is worse than no documentation" and all that.) My understanding is that you're using this Gerrit thing for code review purposes, but issues are still managed on github? (Here)

I got as far as getting my user/keys set up, can SSH to cr... What I can't figure out is how to actually fork a repo (joyent/smartos-live in this case) from github over to cr.joyent. There's multiple references to having admins set things up, and 'see "Getting help" above.', but there is no "Getting help" section I can find.

P.S. FWIW, the whole thing seems a bit offputtingly complicated for folks to participate... I'm sure there are solid reasons for using it, but it's certainly another barrier for outside contributions.

**Comment by rmustacc** [comment]
@Scandalon Sorry you're having trouble following that part. In this case, it sounds like you have a local clone. In that case, all you need to do is follow this section:

https://github.com/joyent/joyent-gerrit/blob/master/docs/user/README.md#using-crjoyentus-with-an-existing-local-workspace

There shouldn't be anything else to manually set up, etc.

**Comment by trentm** [comment]
@Scandalon Yah, it is a large hurdle to jump, esp. for a small and first contribution. I'm sorry for that.
Yes, we are using a mix of GitHub issues and our internal JIRA for issue tracking (which, yes, is far from ideal).  We'd like to get to a public JIRA, but haven't gotten there yet.

Code review: we (the joyent engineering group) made a decision (https://github.com/joyent/rfd/tree/master/rfd/0045) to do more formal code reviews for all our repos (there are over a 100). Gerrit was selected (note that since then GH has come out with some optional more formal review process on PRs).

If you like, I can just take this change. It obviously doesn't need heavy code review.

**Comment by Scandalon** [comment]
Thanks @rmustacc , you were correct, and I now have "CR" set up as the new remote. However I still don't have a good conceptual model of how it's all supposed to work, so...

@trentm Thanks for the extra history/acknowledgement.  I was trying to figure it out for my own knowledge and hopefully future use, but looks like that made it miss todays release. How about if I don't have it submitted properly in a week you just push it through? (I trust it will pass all the unit tests ;)

If I need further help is this the place for it, or the mailing list or...?

**Comment by rmustacc** [comment]
@Scandalon you can get additional help here, or #smartos on freenode may be faster. I'll try to write a brief primer below:

From the guide, you basically can push the changeset you have to gerrit, as though gerrit were just a branch like a fork on github, so you would do this:

```
# Submit code for review as a NEW change in Gerrit.
git push cr HEAD:refs/for/master
```

That will return a URL, which you can then drop here and we'll go and review. If changes are needed, you'd make them locally, commit them, and then squash them. At which point, you'd push it to gerrit using the following:

```
# Submit a new patchset for existing change XYZ in Gerrit
git push cr HEAD:refs/changes/XYZ
```

Where XYZ comes from the id for the original commit. Gerrit will then diff it automatically with the previous one. If you other questions reach or e-mail me. I'll try to figure out how to flesh out that section in the user guide.

**Comment by OranguTech** [comment]
Resurrecting this now that I have a bit more understanding what I'm doing. :/

Ostensibly I'm ready to be added to "the appropriate group" in Gerrit. This is assuming that the github account name does not need to match up to the gerrit account.  GH account is obviously OranguTech, gerrit is Scandalon, note the capital S, through some series of unfortunate events.

**Comment by rmustacc** [comment]
@OranguTech Can you let me know what the gerrit URL is? I'll take care of getting that set up per your request in IRC.

**Comment by OranguTech** [comment]
Thanks @rmustacc  for doing everything from deep technical work to admininistrative account stuff.

URL *should* be ssh://Scandalon@cr.joyent.us/smartos-live.git - but of course I don't actually have any repos/projects on gerrit yet.

**Comment by rmustacc** [comment]
@OranguTech the remote should be joyent/smartos-live.git as opposed to smartos-live.git. At which point, just push to it as mentioned in the comment. Thanks.

**Comment by OranguTech** [comment]
You're right on url, was able to clone a new copy to verify.

Can't push though, even after creating and adding a new key to my gerrit user and ssh agent.:

`notu   master  ~  code  smartos-live  git push cr HEAD:refs/for/master
Counting objects: 12, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (6/6), done.
Writing objects: 100% (12/12), 1013 bytes | 1013.00 KiB/s, done.
Total 12 (delta 8), reused 8 (delta 4)
remote: Resolving deltas: 100% (8/8)
remote: Processing changes: refs: 1, done
To ssh://cr.joyent.us/joyent/smartos-live.git
 ! [remote rejected]   HEAD -> refs/for/master (you are not allowed to upload merges)
error: failed to push some refs to 'ssh://Scandalon@cr.joyent.us/joyent/smartos-live.git'`

**Comment by pfmooney** [comment]
@OranguTech Make sure you've rebased/squashed the change so it's a fast-forward merge onto #master?

**Comment by OranguTech** [comment]
Oh, that was the problem, and technically in the error message, just not clear. Thanks.

**Comment by OranguTech** [comment]
Closing this, adding info to GH issue. (https://github.com/joyent/smartos-live/issues/690) Might be good to explicitly state that in the joyent-gerrit README, not just in this one.

**Pull request closed without merging**
