### PR TITLE
OS-8207 piadm "BOOT BITS?" header is confusing

### PR DESCRIPTION
**Pull request by danmcd**
OS-8208 piadm man page formatting errors

### CODE REVIEW

**Review by bahamat — COMMENTED** [review]
For the man page, looks like you just removed the fences? The code blocks should be indented by eight spaces (and not `\t`) to render properly.

**Comment by danmcd** [comment]
> For the man page, looks like you just removed the fences? The code blocks should be indented by eight spaces (and not `\t`) to render properly.

1.) I did just remove the fences.
2.) They aren't indented by '\t', they are indented by literally one space.  (I had emacs confirm this by uttering "M-x tabify" and literally nothing changed.)

The man rendering on the command line looks find, but the github MD-to-html does mess them up rather badly.

**Comment by bahamat** [comment]
Ok, it looks fine on SmartOS, but on macOS it has some weird highlighting. Do we care?

**Comment by danmcd** [comment]
I don't think we care about it being directly rendered on MacOS.

**Review by bahamat — APPROVED** [review]

**Pull request merged**
