### PR TITLE
imgadm xz compression support for images

### PR DESCRIPTION
**Pull request by xen0l**
This PR adds support for xz compressed images. @trentm what do you think about it?

### CODE REVIEW

**Comment by RSully** [comment]
I'd love to see xz support.

**Comment by bahamat** [comment]
Related:

* [OS-4076][4076]
* [OS-4097][4097]

[4076]: https://smartos.org/bugview/OS-4076
[4097]: https://smartos.org/bugview/OS-4097

Xz support was added to the PI in illumos-extra@0f032ec.

**Comment by RSully** [comment]
@bahamat looks like your illumos-extra link is dead.

**Comment by bahamat** [comment]
Thanks for letting me know. Fixed now.

**Comment by xen0l** [comment]
Any progress on this?

**Comment by bahamat** [comment]
OS-4097 was released on 2015-04-02 so it may work already. Can you test on the new PI?

**Comment by xen0l** [comment]
Sorry for the delay, I will test this against the new version of PI, which is scheduled for tommorrow.

**Comment by xen0l** [comment]
I tested this with the latest platform, which was released on 23.7.2015 and the tests for image creation passed. I had problems with installation though, but the problem was fixed and patch submited as a PR (https://github.com/joyent/node-imgmanifest/pull/2). Is there anything else left to do before this PR is accepted?

**Comment by sjorge** [comment]
@bahamat poke, still looks good to merge to me?

**Comment by xen0l** [comment]
Just reminding myself. Having this accepted would be great. Is there anything else that should be done?

**Comment by trentm** [comment]
looking at it now. Sorry for dropping the ball.

**Comment by trentm** [comment]
Added https://smartos.org/bugview/OS-4690 to have a tracker ticket number for related changes (e.g. to node-imgmanifest.git).

**Pull request closed without merging**
